### ISSUE TITLE
CSS is a little repetitive.

### ISSUE THREAD

**Issue by farishkash** [nalevanko/prj-rev-bwfs-dasmoto#1]
```
body {
  font-family: Helvetica, sans-serif;
}

```
You have this in the body you don't need to repeat in the other classes.  This covers the whole page. 

CSS also has a way to combine selectors so you can reduce the amount of times to repeat yourself.

Example is that you used font-weight: bold; a few times.

You could have called it once with

```
h1,h2, span {
font-weight: bold;
}
```

**Comment by nalevanko** [comment]
Thank you very much for the review. I didn't realize how repetitive the code is, now I see this is something I have to pay special attention to.
